---

- hosts: k8s-cluster:etcd
  gather_facts: True
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults }
    - { role: download, tags: download, when: "not skip_downloads" }
